---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Install dependencies for yq
      apt:
        name:
          - zstd
        state: present
        update_cache: true
      when: ansible_os_family == "Debian"
