---
- name: Prepare
  hosts: all
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install curl
      apt:
        name: curl
        state: present
      when: ansible_os_family == "Debian"
