---
# zsh role defaults
zsh_packages:
  - lsd
  - zsh
  - mercurial
  - zplug

# Oh My Zsh 插件
zsh_plugins:
  - name: zsh-autosuggestions
    repo: https://github.com/zsh-users/zsh-autosuggestions
  - name: zsh-syntax-highlighting
    repo: https://github.com/zsh-users/zsh-syntax-highlighting

# Pokemon color scripts
pokemon_colorscripts_repo: "https://gitlab.com/phoneybadger/pokemon-colorscripts.git"
