---
# fcitx5-rime-ice defaults
fcitx5_rime_ice_install: true
fcitx5_packages:
  - fcitx5
  - fcitx5-rime
  - fcitx5-configtool
plum_install_url: "https://raw.githubusercontent.com/rime/plum/master/rime-install"
rime_ice_recipe: "iDvel/rime-ice:others/recipes/full"
