---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu2404
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    pre_build_image: true
    privileged: true
    network_mode: host
provisioner:
  name: ansible
verifier:
  name: ansible
